export const ColorCardsInfo = [
  {
    subtitle: "HEADLINES, PARAGRAPHS",
    company_name: "Quantox",
    hex: "#000000",
    id: 1,
    background: "#FFFFFF",
    color: "#000000",
    border: " 1px solid #EEEEEE",
  },
  {
    subtitle: "FOOTER",
    company_name: "Quantox",
    hex: "#6E6F72",
    id: 2,
    background: "#6E6F72",
    color: "#FFFFFF",
    border: "",
  },
  {
    subtitle: "CAPTIONS",
    company_name: "Quantox",
    hex: "#B5B5B5",
    id: 3,
    background: "#FFFFFF",
    color: "#B5B5B5",
    border: " 1px solid #EEEEEE",
  },
  {
    subtitle: "CAPTIONS",
    company_name: "Quantox",
    hex: "#98CA3E",
    id: 4,
    background: "#98CA3E",
    color: "#FFFFFF",
    border: "",
  },
];
